// Individual component viewer: one ft electrical part, rendered from its
// precise FreeCAD B-rep.
//
// public/components/<id>.glb and components.json are GENERATED by
// stf-cad/hbw/components_cad.py from the parameter table components.py. The
// same table builds the .FCStd/.step files, so this view, the CAD file and the
// Gemini prompt cannot disagree. The mesh is tessellated at 0.01 mm chordal
// tolerance, and every housing is checked against its datasheet envelope to
// 0.01 mm before anything is written - the "Accuracy check" panel shows that
// check, it is not decoration.

import {
  Bounds, ContactShadows, Environment, Html, Lightformer, Line, OrbitControls, useGLTF,
} from "@react-three/drei";
import { Canvas, useFrame, type ThreeEvent } from "@react-three/fiber";
import { Suspense, useEffect, useMemo, useRef, useState } from "react";
import * as THREE from "three";
import { ErrorBoundary } from "../shared/ErrorBoundary";
import { useJson } from "../shared/data";

const BASE = `${import.meta.env.BASE_URL}components/`;

export type Src = "datasheet" | "photo" | "ft-std" | "assumed" | "booklet";
/** How a sub-part moves when the component is operated (from components.py). */
export interface Motion {
  part: string; type: "spin" | "orbit" | "reciprocate" | "slide" | "squash";
  axis: [number, number, number]; pivot?: [number, number, number]; dps?: number;
  amp?: number; travel?: number; anchor?: [number, number, number]; length?: number;
}
export interface Dim { key: string; label: string; value: number; source: Src; note: string }
export interface Component {
  ft: string; name: string; name_de: string; datasheet: string; material: string;
  facts: { label: string; value: string; source: Src }[];
  dims: Dim[];
  parts: { name: string; material: string; colour: string; inside_envelope: boolean }[];
  verification: { check: string; datasheet_mm: number; model_mm: number; ok: boolean; source?: Src }[];
  overall_mm: [number, number, number];
  mesh: { triangles: number; chordal_tolerance_mm: number };
  files: { glb: string; step: string; fcstd: string };
  used_in: { module: string; part: string; io: string; terminal: string; function: string }[];
  motion?: Motion[];
  operate?: string | null;
  xray?: boolean;
}
export interface ComponentDoc {
  components: Record<string, Component>;
  sources: Record<Src, string>;
}

export function useComponents(): { doc: ComponentDoc | null; err: string | null } {
  const { data, error } = useJson<ComponentDoc>("components/components.json", "components.json missing - run components.py in stf-cad/hbw");
  return { doc: data, err: error };
}

// Physically based materials, chosen per sub-part from the CAD's own material tag.
export function physical(material: string, colour: string): THREE.Material {
  const c = new THREE.Color(colour);
  switch (material) {
    case "steel":
      return new THREE.MeshPhysicalMaterial({ color: c, metalness: 1, roughness: 0.26 });
    case "brass":
      return new THREE.MeshPhysicalMaterial({ color: c, metalness: 1, roughness: 0.32 });
    case "clear":
      return new THREE.MeshPhysicalMaterial({
        color: c, metalness: 0, roughness: 0.05, transmission: 0.85, thickness: 0.6, ior: 1.49,
      });
    case "glass":
      return new THREE.MeshPhysicalMaterial({ color: c, metalness: 0, roughness: 0.08, clearcoat: 1 });
    case "pvc":
      return new THREE.MeshPhysicalMaterial({ color: c, metalness: 0, roughness: 0.55, sheen: 0.3 });
    case "paint":
      return new THREE.MeshPhysicalMaterial({ color: c, metalness: 0, roughness: 0.5 });
    default: // injection-moulded ABS: satin body with a thin glossy skin
      return new THREE.MeshPhysicalMaterial({
        color: c, metalness: 0, roughness: 0.42, clearcoat: 0.35, clearcoatRoughness: 0.4,
      });
  }
}

/** A part that can be operated in the viewer: which sub-part moves, and how far. */
interface Actuator { part: string; travelMm: number }

function Part({
  url, picked, onPick, wire, actuator, pressed = false, onToggle, motion, running = false, xray = false,
}: {
  url: string; picked: string | null; onPick: (n: string | null) => void; wire: boolean;
  actuator?: Actuator | null; pressed?: boolean; onToggle?: () => void;
  motion?: Motion[]; running?: boolean; xray?: boolean;
}) {
  const { scene } = useGLTF(url);
  const model = useMemo(() => scene.clone(true), [scene]);
  // sub-parts driven by the component's motion table
  const driven = useMemo(() => {
    const out: { m: Motion; o: THREE.Object3D }[] = [];
    for (const m of motion ?? []) {
      model.traverse((o) => {
        if ((o.userData as { part?: string }).part === m.part && !(o as THREE.Mesh).isMesh) out.push({ m, o });
      });
      if (!out.some((d) => d.m === m)) {
        model.traverse((o) => {
          if ((o.userData as { part?: string }).part === m.part && !out.some((d) => d.m === m)) out.push({ m, o });
        });
      }
    }
    return out;
  }, [model, motion]);
  const clock = useRef({ theta: 0, u: 0 });
  useFrame((_, dt) => {
    if (!driven.length) return;
    const k = clock.current;
    if (running) k.theta += dt;
    k.u += ((running ? 1 : 0) - k.u) * Math.min(1, dt * 10);
    for (const { m, o } of driven) {
      const ax = new THREE.Vector3(...m.axis).normalize();
      if (m.type === "spin" || m.type === "orbit") {
        const piv = new THREE.Vector3(...(m.pivot ?? [0, 0, 0])).multiplyScalar(0.001);
        const q = new THREE.Quaternion().setFromAxisAngle(ax, THREE.MathUtils.degToRad((m.dps ?? 360) * k.theta));
        o.quaternion.copy(q);
        o.position.copy(piv.clone().sub(piv.clone().applyQuaternion(q)));
      } else if (m.type === "reciprocate") {
        const th = THREE.MathUtils.degToRad((m.dps ?? 360) * k.theta);
        o.position.copy(ax.multiplyScalar(((m.amp ?? 0) / 2) * (1 - Math.cos(th)) * 0.001));
      } else if (m.type === "slide") {
        o.position.copy(ax.multiplyScalar((m.travel ?? 0) * k.u * 0.001));
      } else if (m.type === "squash") {
        const len = m.length ?? 1;
        const sc = (len - (m.travel ?? 0) * k.u) / len;
        const i = Math.abs(m.axis[0]) > 0.5 ? 0 : Math.abs(m.axis[1]) > 0.5 ? 1 : 2;
        const anc = (m.anchor ?? [0, 0, 0])[i] * 0.001;
        o.scale.setComponent(i, sc);
        o.position.setComponent(i, anc * (1 - sc));
      }
    }
  });
  const moving = useRef<THREE.Object3D | null>(null);
  useEffect(() => {
    moving.current = null;
    if (!actuator) return;
    model.traverse((o) => {
      if ((o.userData as { part?: string }).part === actuator.part) moving.current = o;
    });
  }, [model, actuator]);
  // Ease the actuator to its target: pressed = pushed down by its travel. The
  // node sits under the glb root, whose frame is the part's own Z-up, in metres.
  useFrame((_, dt) => {
    const m = moving.current;
    if (!m || !actuator) return;
    const target = pressed ? -actuator.travelMm * 0.001 : 0;
    m.position.z += (target - m.position.z) * Math.min(1, dt * 18);
  });
  useEffect(() => {
    model.traverse((o) => {
      const m = o as THREE.Mesh;
      if (!m.isMesh) return;
      const u = m.userData as { material?: string; colour?: string; part?: string };
      const mat = physical(u.material ?? "abs", u.colour ?? "#888") as THREE.MeshPhysicalMaterial;
      // X-ray: the enclosures go glassy so the mechanism inside can be watched
      if (xray && ["housing", "u_gearbox", "coil"].includes(u.part ?? "")) {
        mat.transparent = true;
        mat.opacity = 0.16;
        mat.depthWrite = false;
      }
      if (u.part === picked) {
        mat.emissive = new THREE.Color("#4aa3c8");
        mat.emissiveIntensity = 0.55;
      }
      mat.wireframe = wire;
      m.material = mat;
      m.castShadow = m.receiveShadow = true;
    });
  }, [model, picked, wire, xray]);
  return (
    <primitive
      object={model}
      onClick={(e: ThreeEvent<MouseEvent>) => {
        e.stopPropagation();
        const part = (e.object.userData as { part?: string }).part ?? null;
        // the actuator OPERATES the switch; selecting it too would tint it pink
        if (actuator && part === actuator.part) onToggle?.();
        else onPick(part);
      }}
    />
  );
}

/** A dimension line with extension ticks, drawn in the part's own mm frame. */
function DimLine({ a, b, label, off }: { a: number[]; b: number[]; label: string; off: number[] }) {
  const A = new THREE.Vector3(...(a as [number, number, number])).add(new THREE.Vector3(...(off as [number, number, number])));
  const B = new THREE.Vector3(...(b as [number, number, number])).add(new THREE.Vector3(...(off as [number, number, number])));
  const mid = A.clone().add(B).multiplyScalar(0.5);
  return (
    <group>
      <Line points={[A, B]} color="#4aa3c8" lineWidth={1.5} />
      <Line points={[new THREE.Vector3(...(a as [number, number, number])), A]} color="#4aa3c8" lineWidth={0.8} dashed dashSize={0.6} gapSize={0.4} />
      <Line points={[new THREE.Vector3(...(b as [number, number, number])), B]} color="#4aa3c8" lineWidth={0.8} dashed dashSize={0.6} gapSize={0.4} />
      <Html position={mid} center className="dim-label">{label}</Html>
    </group>
  );
}

const SRC_LABEL: Record<Src, string> = {
  datasheet: "datasheet", photo: "photo", "ft-std": "ft std", assumed: "measure", booklet: "booklet",
};

export function ComponentView({ id, doc }: { id: string; doc: ComponentDoc }) {
  const c = doc.components[id];
  const [picked, setPicked] = useState<string | null>(null);
  const [showDims, setShowDims] = useState(true);
  const [wire, setWire] = useState(false);
  const [spin, setSpin] = useState(false);
  // Operable components. The mini switch's actuator stands 2.5 mm proud; pressed,
  // it goes down 2.0 mm (travel not in the datasheet - assumed, like btn_h).
  const actuator: Actuator | null = useMemo(
    () => (id === "mini_switch" ? { part: "actuator", travelMm: 2.0 } : null),
    [id],
  );
  const [on, setOn] = useState(false);
  useEffect(() => setOn(false), [id]);
  const motion = c.motion ?? [];
  const operable = !!actuator || motion.length > 0;
  const [xray, setXray] = useState(false);
  useEffect(() => setXray(!!c.xray), [id, c.xray]);
  // IR track sensor: where the black track is, mm along the housing (x)
  const [track, setTrack] = useState(9);
  const isIr = id === "ir_track_sensor";
  const [filter, setFilter] = useState<Src | "all">("all");
  useEffect(() => setPicked(null), [id]);

  const g = (k: string) => c.dims.find((d) => d.key === k)?.value ?? 0;
  const [L, W, H] = [g("L"), g("W"), g("H")];
  const f = (v: number) => `${v.toFixed(2)} mm`;
  const part = c.parts.find((p) => p.name === picked);
  const allOk = c.verification.every((v) => v.ok);
  const dims = c.dims.filter((d) => filter === "all" || d.source === filter);
  const counts = c.dims.reduce<Record<string, number>>((a, d) => ((a[d.source] = (a[d.source] ?? 0) + 1), a), {});

  return (
    <div className="body">
      <div className="viewport comp-viewport">
        <div className="comp-toolbar">
          <label><input type="checkbox" checked={showDims} onChange={(e) => setShowDims(e.target.checked)} /> Dimensions</label>
          <label><input type="checkbox" checked={wire} onChange={(e) => setWire(e.target.checked)} /> Wireframe</label>
          <label><input type="checkbox" checked={spin} onChange={(e) => setSpin(e.target.checked)} /> Turntable</label>
          {c.xray && (
            <label><input type="checkbox" checked={xray} onChange={(e) => setXray(e.target.checked)} /> X-ray</label>
          )}
          {operable && (
            <button
              className={`tick-toggle ${on ? "on" : ""}`}
              role="switch"
              aria-checked={on}
              onClick={() => setOn((v) => !v)}
            >
              <span className="tick-box">{on ? "✓" : ""}</span>{" "}
              {actuator ? (on ? "ON — pressed" : "OFF — released") : `${c.operate ?? "operate"}: ${on ? "ON" : "OFF"}`}
            </button>
          )}
          {isIr && (
            <label className="track-slider">
              track at x = {track.toFixed(0)} mm
              <input type="range" min={-8} max={38} step={0.5} value={track}
                onChange={(e) => setTrack(Number(e.target.value))} />
            </label>
          )}
          <span className="comp-hint">
            drag to orbit · scroll to zoom · click a sub-part{actuator ? " · click the red actuator to switch" : ""}
          </span>
        </div>
        <ErrorBoundary>
          <Canvas
            key={id}
            shadows
            dpr={[1, 2]}
            gl={{ preserveDrawingBuffer: true, toneMapping: THREE.ACESFilmicToneMapping }}
            camera={{ position: [-0.1, 0.07, 0.11], fov: 32, near: 0.001, far: 5 }}
            onPointerMissed={() => setPicked(null)}
          >
            {/* mid-grey studio backdrop: black ft housings vanish against near-black */}
            <color attach="background" args={["#2b3540"]} />
            <hemisphereLight args={["#e8eef4", "#1a2028", 0.55]} />
            {/* studio lighting baked from light panels - no network HDRI needed */}
            <Environment resolution={256}>
              <Lightformer intensity={3} position={[0, 3, 2]} scale={[6, 2, 1]} />
              <Lightformer intensity={1.8} position={[-4, 1, -1]} rotation-y={Math.PI / 2} scale={[4, 3, 1]} />
              <Lightformer intensity={1.4} position={[4, 0.5, 1]} rotation-y={-Math.PI / 2} scale={[3, 3, 1]} />
              <Lightformer intensity={2} position={[0, 1, -4]} scale={[6, 3, 1]} />
              <Lightformer form="ring" intensity={2} position={[1, 2, 4]} scale={1.5} />
            </Environment>
            <directionalLight position={[0.1, 0.2, 0.1]} intensity={1.4} castShadow shadow-mapSize={[2048, 2048]} />
            {/* rim light from behind, so dark edges separate from the backdrop */}
            <directionalLight position={[-0.05, 0.08, -0.15]} intensity={1.6} color="#cfe6ff" />
            <Suspense fallback={<Html center className="dim-label">loading {c.name}…</Html>}>
              <Bounds fit clip observe margin={1.5}>
                <group>
                  <Part url={`${BASE}${c.files.glb}`} picked={picked} onPick={setPicked} wire={wire}
                    actuator={actuator} pressed={on} onToggle={() => setOn((v) => !v)}
                    motion={motion} running={on} xray={xray} />
                  {isIr && (
                    // white card with a 10 mm black track, 15 mm in front of the windows
                    <group rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
                      <mesh position={[L / 2, -15, H / 2]} rotation={[Math.PI / 2, 0, 0]}>
                        <planeGeometry args={[60, 30]} />
                        <meshStandardMaterial color="#f4f4f0" side={THREE.DoubleSide} />
                      </mesh>
                      <mesh position={[track, -14.9, H / 2]} rotation={[Math.PI / 2, 0, 0]}>
                        <planeGeometry args={[10, 30]} />
                        <meshStandardMaterial color="#111" side={THREE.DoubleSide} />
                      </mesh>
                    </group>
                  )}
                  {showDims && (
                    // the part's own frame: mm, Z up -> same transform as the glb root
                    <group rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
                      <DimLine a={[0, 0, 0]} b={[L, 0, 0]} off={[0, -6, 0]} label={f(L)} />
                      <DimLine a={[L, 0, 0]} b={[L, W, 0]} off={[6, 0, 0]} label={f(W)} />
                      <DimLine a={[0, 0, 0]} b={[0, 0, H]} off={[-6, -6, 0]} label={f(H)} />
                      {id === "encoder_motor" && (
                        <DimLine a={[-g("shaft_l"), W / 2, H / 2 + g("shaft_d") / 2]} b={[0, W / 2, H / 2 + g("shaft_d") / 2]}
                          off={[0, 0, 8]} label={`shaft ${f(g("shaft_l"))} · Ø${g("shaft_d").toFixed(2)} · AF ${(g("shaft_d") - 2 * g("flat")).toFixed(2)}`} />
                      )}
                    </group>
                  )}
                </group>
              </Bounds>
            </Suspense>
            <ContactShadows position={[0, -0.0005, 0]} opacity={0.55} scale={0.3} blur={2.2} far={0.08} />
            <OrbitControls makeDefault enableDamping autoRotate={spin} autoRotateSpeed={1.2} />
          </Canvas>
        </ErrorBoundary>
      </div>

      <aside className="sidebar">
        <section className="panel">
          <h2>
            {c.name} <span className="tag idle">ft {c.ft}</span>
          </h2>
          <p className="clock">{c.name_de} · {c.material}</p>
          <p className="clock">
            Built in FreeCAD from <code>components.py</code> · {c.mesh.triangles.toLocaleString()} triangles
            at {c.mesh.chordal_tolerance_mm} mm chordal tolerance · overall{" "}
            {c.overall_mm.map((v) => v.toFixed(2)).join(" × ")} mm
          </p>
          <p className="comp-files">
            <a href={`${BASE}${c.files.step}`} download>Download STEP</a>
            <span className="clock"> · FreeCAD: <code>{c.files.fcstd}</code></span>
          </p>
        </section>

        <section className="panel">
          <h2>
            Accuracy check <span className={`tag ${allOk ? "run" : "warn"}`}>{allOk ? "PASS" : "FAIL"}</span>
          </h2>
          <table className="tbl">
            <thead><tr><th>check</th><th className="num">spec</th><th className="num">model</th><th>source</th></tr></thead>
            <tbody>
              {c.verification.map((v) => (
                <tr key={v.check}>
                  <td>{v.check}</td>
                  <td className="num">{v.datasheet_mm.toFixed(2)}</td>
                  <td className={`num ${v.ok ? "" : "warn"}`}>{v.model_mm.toFixed(3)}</td>
                  <td><span className={`src src-${v.source ?? "datasheet"}`}>{SRC_LABEL[v.source ?? "datasheet"]}</span></td>
                </tr>
              ))}
            </tbody>
          </table>
          <p className="clock">
            Exact B-rep bounding box against the table, tolerance 0.01 mm. The model is only as
            true as its spec: a “measure” spec means the real part has not been measured yet.
          </p>
        </section>

        {actuator && <SwitchState on={on} onToggle={() => setOn((v) => !v)} />}
        {id === "solenoid_valve" && <ValveState on={on} onToggle={() => setOn((v) => !v)} />}
        {id === "compressor" && <PumpState on={on} />}
        {id === "pneumatic_cylinder" && <CylinderState on={on} />}
        {id === "s_motor" && <MotorState on={on} />}
        {isIr && <TrackState track={track} xs={[g("win_x"), L - g("win_x")]} r={g("win_d") / 2} />}

        <section className="panel">
          <h2>Selected sub-part</h2>
          {part ? (
            <table className="tbl"><tbody>
              <tr><th>name</th><td>{part.name}</td></tr>
              <tr><th>material</th><td>{part.material}</td></tr>
              <tr><th>envelope</th><td>{part.inside_envelope ? "inside the datasheet envelope" : "protrudes beyond it"}</td></tr>
            </tbody></table>
          ) : (
            <p className="clock">Click the model. Sub-parts: {c.parts.map((p) => p.name).join(", ")}</p>
          )}
        </section>

        <section className="panel">
          <h2>Ratings and function</h2>
          <table className="tbl"><tbody>
            {c.facts.map((x) => (
              <tr key={x.label}>
                <th>{x.label}</th><td>{x.value}</td>
                <td><span className={`src src-${x.source}`}>{SRC_LABEL[x.source]}</span></td>
              </tr>
            ))}
          </tbody></table>
          <p className="clock">Source: {c.datasheet}</p>
        </section>

        <section className="panel">
          <h2>Dimensions</h2>
          <div className="src-filter">
            {(["all", "datasheet", "booklet", "photo", "ft-std", "assumed"] as const).filter((s) => s === "all" || counts[s]).map((s) => (
              <button key={s} className={filter === s ? "on" : ""} onClick={() => setFilter(s)}>
                {s === "all" ? `all ${c.dims.length}` : `${SRC_LABEL[s]} ${counts[s] ?? 0}`}
              </button>
            ))}
          </div>
          <table className="tbl">
            <tbody>
              {dims.map((d) => (
                <tr key={d.key} title={d.note || doc.sources[d.source]}>
                  <td>{d.label}</td>
                  <td className="num">{d.value.toFixed(2)}</td>
                  <td><span className={`src src-${d.source}`}>{SRC_LABEL[d.source]}</span></td>
                </tr>
              ))}
            </tbody>
          </table>
          <p className="clock">
            Only “datasheet” values are authoritative. “measure” = not documented anywhere: confirm
            with calipers, change <code>components.py</code>, rebuild.
          </p>
        </section>

        <section className="panel">
          <h2>Used in the factory <span className="tag idle">{c.used_in.length}×</span></h2>
          <table className="tbl">
            <thead><tr><th>module</th><th>part</th><th>I/O</th></tr></thead>
            <tbody>
              {c.used_in.map((u) => (
                <tr key={u.module + u.part} title={u.function}>
                  <td>{u.module}</td><td>{u.part}</td><td>{u.io}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </section>
      </aside>
    </div>
  );
}

/** Contact state of the mini switch, straight from its datasheet: contact 1 is
    the common; released it touches 2 (normally closed), pressed it touches 3
    (normally open). */
function SwitchState({ on, onToggle }: { on: boolean; onToggle: () => void }) {
  // blade from the common (1) to 3 when pressed, to 2 when released
  const tip = on ? { x: 92, y: 22 } : { x: 92, y: 78 };
  return (
    <section className="panel">
      <h2>
        Switch state <span className={`tag ${on ? "run" : "idle"}`}>{on ? "ON" : "OFF"}</span>
      </h2>
      <button className={`tick-toggle big ${on ? "on" : ""}`} role="switch" aria-checked={on} onClick={onToggle}>
        <span className="tick-box">{on ? "✓" : ""}</span>
        {on ? "Pressed — click to release" : "Released — click to press"}
      </button>
      <svg viewBox="0 0 150 100" className="switch-schematic" aria-label="contact schematic">
        <line x1="10" y1="50" x2="40" y2="50" className="wire" />
        <circle cx="40" cy="50" r="4" className="node" />
        <text x="30" y="68">1</text>
        <line x1="40" y1="50" x2={tip.x} y2={tip.y} className={`blade ${on ? "on" : ""}`} />
        <line x1="100" y1="22" x2="140" y2="22" className={`wire ${on ? "live" : ""}`} />
        <circle cx="100" cy="22" r="4" className="node" />
        <text x="104" y="14">3 (NO)</text>
        <line x1="100" y1="78" x2="140" y2="78" className={`wire ${on ? "" : "live"}`} />
        <circle cx="100" cy="78" r="4" className="node" />
        <text x="104" y="96">2 (NC)</text>
      </svg>
      <table className="tbl">
        <tbody>
          <tr><th>contacts 1–3 (NO)</th><td className={on ? "ok" : ""}>{on ? "closed" : "open"}</td></tr>
          <tr><th>contacts 1–2 (NC)</th><td className={on ? "" : "ok"}>{on ? "open" : "closed"}</td></tr>
          <tr><th>input, wired NO</th><td className="num">{on ? "1" : "0"}</td></tr>
          <tr><th>input, wired NC</th><td className="num">{on ? "0" : "1"}</td></tr>
        </tbody>
      </table>
      <p className="clock">Digital input, 5 kΩ (TXT / RevPi DIO). Rated 2 A / 50 V.</p>
    </section>
  );
}

/** 3/2-way valve, drawn after the booklet's Abb. 5: energised, the plunger (b)
    lifts against the spring (c) and 1 (P) feeds 2 (A); released, the spring
    closes P and 2 (A) vents through 3 (R). */
function ValveState({ on, onToggle }: { on: boolean; onToggle: () => void }) {
  return (
    <section className="panel">
      <h2>Valve state <span className={`tag ${on ? "run" : "idle"}`}>{on ? "ENERGISED" : "OFF"}</span></h2>
      <button className={`tick-toggle big ${on ? "on" : ""}`} role="switch" aria-checked={on} onClick={onToggle}>
        <span className="tick-box">{on ? "✓" : ""}</span>
        {on ? "Coil energised — click to release" : "Coil off — click to energise"}
      </button>
      <svg viewBox="0 0 200 120" className="switch-schematic valve-svg" aria-label="valve flow">
        <rect x="70" y="20" width="60" height="80" rx="4" className="body" />
        <text x="100" y="14" textAnchor="middle">1 (P)</text>
        <line x1="100" y1="0" x2="100" y2="20" className={`pipe ${on ? "live" : "dead"}`} />
        <text x="178" y="52" textAnchor="middle">2 (A)</text>
        <line x1="130" y1="60" x2="200" y2="60" className={`pipe ${"live"}`} />
        <text x="100" y="118" textAnchor="middle">3 (R)</text>
        <line x1="100" y1="100" x2="100" y2="110" className={`pipe ${on ? "dead" : "live"}`} />
        <rect x="92" y={on ? 30 : 38} width="16" height="40" className="core" />
        <path d={on ? "M100 22 L100 58 L150 58" : "M150 62 L100 62 L100 108"} className="flow" markerEnd="url(#arr)" />
        <defs>
          <marker id="arr" markerWidth="8" markerHeight="8" refX="6" refY="4" orient="auto">
            <path d="M0,0 L8,4 L0,8 z" className="arrowhead" />
          </marker>
        </defs>
      </svg>
      <table className="tbl"><tbody>
        <tr><th>1 (P) → 2 (A)</th><td className={on ? "ok" : ""}>{on ? "open — the cylinder is pressurised" : "closed by the spring"}</td></tr>
        <tr><th>2 (A) → 3 (R)</th><td className={on ? "" : "ok"}>{on ? "closed" : "open — the cylinder vents"}</td></tr>
        <tr><th>plunger (b)</th><td>{on ? "pulled up by the coil (a)" : "pushed down by the spring (c)"}</td></tr>
      </tbody></table>
      <p className="clock">Normally closed. Two wires: a P-switching PLC output and ground.</p>
    </section>
  );
}

/** The membrane pump of the booklet's Abb. 4, phase by phase. */
function PumpState({ on }: { on: boolean }) {
  return (
    <section className="panel">
      <h2>Membrane pump <span className={`tag ${on ? "run" : "idle"}`}>{on ? "PUMPING" : "OFF"}</span></h2>
      <ol className="pump-steps">
        <li><b>Kurbeltrieb</b> (crank): the motor turns an eccentric; its pin drives the con-rod.</li>
        <li><b>Kolben</b> (piston) moves right: the <b>Membran</b> is pulled back and air enters through the
          <b> Einlassventil</b>.</li>
        <li>Piston moves left: the membrane pushes the air out through the <b>Auslassventil</b> in the
          <b> Deckel</b> (cover) to the nipple.</li>
      </ol>
      <table className="tbl"><tbody>
        <tr><th>overpressure</th><td>0.7 bar</td></tr>
        <tr><th>current</th><td>max 70 mA at 24 VDC</td></tr>
      </tbody></table>
      <p className="clock">Tick X-ray to watch the crank, piston and membrane inside the housing.</p>
    </section>
  );
}

function CylinderState({ on }: { on: boolean }) {
  return (
    <section className="panel">
      <h2>Cylinder <span className={`tag ${on ? "run" : "idle"}`}>{on ? "EXTENDED" : "RETRACTED"}</span></h2>
      <table className="tbl"><tbody>
        <tr><th>valve</th><td>{on ? "energised: P → A, the rear chamber is pressurised" : "off: A → R, vented"}</td></tr>
        <tr><th>piston rod</th><td>{on ? "out by the full stroke" : "held in by the spring"}</td></tr>
        <tr><th>spring</th><td>{on ? "compressed" : "relaxed"}</td></tr>
      </tbody></table>
      <p className="clock">
        Vacuum without a vacuum pump (booklet p.10): two cylinders coupled back to back. Pressurise one,
        both rods extend, and the chamber closed off by the suction cup grows, so its pressure drops below
        ambient.
      </p>
    </section>
  );
}

function MotorState({ on }: { on: boolean }) {
  return (
    <section className="panel">
      <h2>Drive train <span className={`tag ${on ? "run" : "idle"}`}>{on ? "RUNNING" : "OFF"}</span></h2>
      <table className="tbl"><tbody>
        <tr><th>motor (no load)</th><td className="num">10 700 rpm</td></tr>
        <tr><th>U-Getriebe</th><td className="num">64.8 : 1</td></tr>
        <tr><th>side output (no load)</th><td className="num">165 rpm</td></tr>
        <tr><th>torque at the motor</th><td className="num">max 5 mNm</td></tr>
      </tbody></table>
      <p className="clock">The animation is slowed: the worm really turns 65× faster than the wheel. Tick X-ray to see them mesh.</p>
    </section>
  );
}

/** Two channels: each window has an IR emitter and receiver; a black track in
    front of a window absorbs the IR and that channel reports it. */
function TrackState({ track, xs, r }: { track: number; xs: number[]; r: number }) {
  const sees = xs.map((x) => Math.abs(track - x) < 5 + r);
  return (
    <section className="panel">
      <h2>Track sensor</h2>
      <table className="tbl"><tbody>
        {sees.map((s, i) => (
          <tr key={i}>
            <th>channel {i + 1} ({i === 0 ? "black wire" : "yellow wire"})</th>
            <td className={s ? "ok" : ""}>{s ? "track under the window" : "white ground"}</td>
          </tr>
        ))}
      </tbody></table>
      <p className="clock">
        Range 5–30 mm; the card here is 15 mm away. Which logic level means “black” is not printed in the
        booklet — check it on the machine before writing the PLC program.
      </p>
    </section>
  );
}
