"""
Upgrade 14, step 3 - the MQTT server: Eclipse Mosquitto, configured for the cell.

SECURITY (IEC 62443 zone Z3, docs/SECURITY.md S15)
  - one listener, MQTT over TLS 1.3 on 127.0.0.1, with a certificate from the project's own CA
    (.cache/uns/pki); no plain-text listener;
  - no anonymous clients; one account per role, each with a random password;
  - an access list per role (least privilege):
      stf-edge     publishes only its own node's and devices' Sparkplug topics, its NDEATH
                   will included; reads only its commands and the primary host's STATE
      stf-scada    the primary host application: reads the group, writes commands and its
                   STATE, and is the only writer of the Unified Namespace
      stf-viewer   reads the Unified Namespace, nothing else, writes nothing
      stf-auditor  reads everything (the conformance monitor of uns/check.py), writes nothing
"""
import datetime
import ipaddress
import os
import secrets
import shutil
import socket
import subprocess
import time
from pathlib import Path

from cryptography import x509
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.x509.oid import ExtendedKeyUsageOID, NameOID

from uns import namespace as N

HBW = Path(__file__).resolve().parents[1]
CACHE = HBW / ".cache" / "uns"
PORT = 8883
ROLES = ("stf-edge", "stf-scada", "stf-viewer", "stf-auditor")


def mosquitto_bin():
    for c in (shutil.which("mosquitto"), "/opt/homebrew/opt/mosquitto/sbin/mosquitto", "/usr/sbin/mosquitto",
              "/usr/local/sbin/mosquitto"):
        if c and os.path.exists(c):
            return c
    raise SystemExit("mosquitto not found: brew install mosquitto (or apt install mosquitto)")


def passwd_bin():
    return shutil.which("mosquitto_passwd") or str(Path(mosquitto_bin()).parent.parent / "bin" / "mosquitto_passwd")


def acl(edge=N.EDGE, group=N.GROUP, host=N.HOST_ID, root=N.UNS_ROOT):
    sp = f"{N.NAMESPACE}/{group}"
    return f"""# generated by uns/broker.py - least privilege per role
user stf-edge
topic write {sp}/NBIRTH/{edge}
topic write {sp}/NDATA/{edge}
topic write {sp}/NDEATH/{edge}
topic write {sp}/DBIRTH/{edge}/+
topic write {sp}/DDATA/{edge}/+
topic write {sp}/DDEATH/{edge}/+
topic read {sp}/NCMD/{edge}
topic read {sp}/DCMD/{edge}/+
topic read {N.NAMESPACE}/STATE/{host}

user stf-scada
topic readwrite {N.NAMESPACE}/STATE/{host}
topic read {sp}/#
topic write {sp}/NCMD/+
topic write {sp}/DCMD/+/+
topic readwrite {root}/#

user stf-viewer
topic read {root}/#

user stf-auditor
topic read #
"""


def _pki(d: Path):
    """A CA and a server certificate for 127.0.0.1/localhost (ECDSA P-256), made once."""
    d.mkdir(parents=True, exist_ok=True)
    ca_crt, srv_crt, srv_key = d / "ca.pem", d / "server.pem", d / "server.key"
    if ca_crt.exists() and srv_crt.exists() and srv_key.exists():
        return ca_crt, srv_crt, srv_key
    now = datetime.datetime.now(datetime.UTC)
    ca_key = ec.generate_private_key(ec.SECP256R1())
    ca_name = x509.Name([x509.NameAttribute(NameOID.ORGANIZATION_NAME, "STF digital twin project"),
                         x509.NameAttribute(NameOID.COMMON_NAME, "STF cell MQTT CA")])
    ca = (x509.CertificateBuilder().subject_name(ca_name).issuer_name(ca_name).public_key(ca_key.public_key())
          .serial_number(x509.random_serial_number()).not_valid_before(now).not_valid_after(now + datetime.timedelta(days=365))
          .add_extension(x509.BasicConstraints(ca=True, path_length=0), critical=True)
          .add_extension(x509.KeyUsage(False, False, False, False, False, True, True, False, False), critical=True)
          .sign(ca_key, hashes.SHA256()))
    key = ec.generate_private_key(ec.SECP256R1())
    srv = (x509.CertificateBuilder()
           .subject_name(x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, "localhost")]))
           .issuer_name(ca_name).public_key(key.public_key()).serial_number(x509.random_serial_number())
           .not_valid_before(now).not_valid_after(now + datetime.timedelta(days=365))
           .add_extension(x509.SubjectAlternativeName([x509.DNSName("localhost"),
                                                       x509.IPAddress(ipaddress.ip_address("127.0.0.1"))]), critical=False)
           .add_extension(x509.ExtendedKeyUsage([ExtendedKeyUsageOID.SERVER_AUTH]), critical=False)
           .add_extension(x509.BasicConstraints(ca=False, path_length=None), critical=True)
           .sign(ca_key, hashes.SHA256()))
    ca_crt.write_bytes(ca.public_bytes(serialization.Encoding.PEM))
    srv_crt.write_bytes(srv.public_bytes(serialization.Encoding.PEM))
    srv_key.write_bytes(key.private_bytes(serialization.Encoding.PEM, serialization.PrivateFormat.PKCS8,
                                          serialization.NoEncryption()))
    os.chmod(srv_key, 0o600)
    return ca_crt, srv_crt, srv_key


class Broker:
    """A Mosquitto process with this cell's configuration. `insecure` builds the mutants of the check."""

    def __init__(self, port=PORT, workdir=CACHE / "run", passwords=None, allow_anonymous=False, extra_acl=""):
        self.port, self.dir = port, Path(workdir)
        self.passwords = passwords or {r: secrets.token_urlsafe(18) for r in ROLES}
        self.allow_anonymous, self.extra_acl = allow_anonymous, extra_acl
        self.proc = None
        self.ca, self.cert, self.key = _pki(CACHE / "pki")

    def write(self):
        d = self.dir
        if d.exists():
            shutil.rmtree(d)
        d.mkdir(parents=True)
        pw = d / "passwd"
        pw.touch(mode=0o600)
        for user, p in self.passwords.items():
            subprocess.run([passwd_bin(), "-b", str(pw), user, p], check=True, capture_output=True)
        (d / "acl").write_text(acl() + self.extra_acl)
        os.chmod(d / "acl", 0o600)
        (d / "mosquitto.conf").write_text(f"""# generated by uns/broker.py
per_listener_settings false
allow_anonymous {"true" if self.allow_anonymous else "false"}
password_file {pw}
acl_file {d / "acl"}
persistence false
log_dest file {d / "mosquitto.log"}
log_type error
log_type warning
log_type notice

listener {self.port} 127.0.0.1
cafile {self.ca}
certfile {self.cert}
keyfile {self.key}
tls_version tlsv1.3
""")
        return d / "mosquitto.conf"

    def start(self):
        conf = self.write()
        self.proc = subprocess.Popen([mosquitto_bin(), "-c", str(conf)], stdout=subprocess.DEVNULL, stderr=subprocess.PIPE)
        t0 = time.time()
        while time.time() - t0 < 10:
            if self.proc.poll() is not None:
                raise RuntimeError(f"mosquitto exited: {self.proc.stderr.read().decode()[-500:]}")
            try:
                socket.create_connection(("127.0.0.1", self.port), timeout=0.2).close()
                return self
            except OSError:
                time.sleep(0.1)
        raise RuntimeError("mosquitto did not open its port")

    def stop(self):
        if self.proc and self.proc.poll() is None:
            self.proc.terminate()
            try:
                self.proc.wait(5)
            except subprocess.TimeoutExpired:
                self.proc.kill()

    def __enter__(self):
        return self.start()

    def __exit__(self, *a):
        self.stop()
