"""
Upgrade 13 - compile the generated program: IEC 61131-3 -> C (MatIEC) -> WebAssembly.

    STF_VARIANT=up12 python3 -m sil.build        (from stf-cad/hbw)

MatIEC (iec2c, the IEC compiler inside OpenPLC and Beremiz) parses and type-checks
the program and emits C. A small runtime (glue.c, written here) gives every
located variable its place in a flat I/O image and advances the IEC clock one
task interval per scan. clang compiles both to one WebAssembly module with no
imports: the same binary runs the proof (sil/run.py, under Node) and the
public twin (web/src/sil).

Tools (not in the repository; see docs/UPGRADE_PLAN.md, Upgrade 13):
  STF_MATIEC    the MatIEC checkout with a built iec2c   (default ~/workspace/stf-hw/.cache/matiec)
  STF_CLANG     a clang with the wasm32 target            (default Homebrew llvm)
  STF_WASI      the WASI sysroot and runtimes             (default Homebrew wasi-libc / wasi-runtimes)
"""
import hashlib
import json
import os
import re
import shutil
import subprocess

from sil import iec

HERE = os.path.dirname(os.path.abspath(__file__))
WORK = os.path.join(HERE, "..", ".cache", "sil")
OUT = os.path.expanduser("~/workspace/stf-hw/web/public/sil")
MATIEC = os.environ.get("STF_MATIEC", os.path.expanduser("~/workspace/stf-hw/.cache/matiec"))
CLANG = os.environ.get("STF_CLANG", "/opt/homebrew/opt/llvm/bin/clang")
WASM_LD = os.environ.get("STF_WASM_LD", "/opt/homebrew/opt/lld/bin/wasm-ld")
SYSROOT = os.environ.get("STF_WASI", "/opt/homebrew/opt/wasi-libc/share/wasi-sysroot")
RUNTIMES = os.environ.get("STF_WASI_RT", "/opt/homebrew/opt/wasi-runtimes/share/wasi-runtimes")

# the I/O image: how many of each the runtime reserves
IMAGE = {"ix": 256, "qx": 256, "iw": 16, "id": 16, "mw": 256}
EXPORTS = ["plc_init", "plc_scan", "plc_ix", "plc_qx", "plc_iw", "plc_id", "plc_mw", "plc_tick_ns"]


def glue(located):
    """The runtime: storage for every located variable, inside the flat image."""
    L = ["/* Generated by stf-cad/hbw/sil/build.py: the runtime of the MatIEC program. */",
         '#include "iec_std_lib.h"',
         *(f"static {t} {n}_[{k}];" for n, t, k in (("ix", "BOOL", IMAGE["ix"]), ("qx", "BOOL", IMAGE["qx"]),
                                                       ("iw", "INT", IMAGE["iw"]), ("id", "REAL", IMAGE["id"]),
                                                       ("mw", "INT", IMAGE["mw"])))]
    for typ, name, area, size, a, b in located:
        if size == "X":
            idx = int(a) * 8 + int(b)
            arr = "ix_" if area == "I" else "qx_"
        elif area == "I" and size == "W":
            idx, arr = int(a), "iw_"
        elif area == "I" and size == "D":
            idx, arr = int(a), "id_"
        elif area == "M" and size == "W":
            idx, arr = int(a), "mw_"
        else:
            raise ValueError(f"no image area for {name}")
        L.append(f"{typ} *{name} = &{arr}[{idx}];")
    L += ["TIME __CURRENT_TIME;",
          "extern unsigned long long common_ticktime__;",
          "void config_init__(void);",
          "void config_run__(unsigned long tick);",
          "static unsigned long tick_;",
          "void plc_init(void) { tick_ = 0; __CURRENT_TIME.tv_sec = 0; __CURRENT_TIME.tv_nsec = 0; config_init__(); }",
          "void plc_scan(void) {",
          "  config_run__(tick_++);",
          "  __CURRENT_TIME.tv_nsec += common_ticktime__;",
          "  while (__CURRENT_TIME.tv_nsec >= 1000000000) { __CURRENT_TIME.tv_nsec -= 1000000000; __CURRENT_TIME.tv_sec++; }",
          "}",
          "BOOL *plc_ix(void) { return ix_; }", "BOOL *plc_qx(void) { return qx_; }",
          "INT *plc_iw(void) { return iw_; }", "REAL *plc_id(void) { return id_; }",
          "INT *plc_mw(void) { return mw_; }",
          "unsigned long long plc_tick_ns(void) { return common_ticktime__; }", ""]
    return "\n".join(L)


def build(out=OUT):
    for tool in (os.path.join(MATIEC, "iec2c"), CLANG, WASM_LD):
        if not os.path.exists(tool):
            raise SystemExit(f"missing {tool}: see the docstring of sil/build.py")
    src, starts = iec.project()
    io = iec.io_map()
    work = os.path.join(WORK, "plc")
    shutil.rmtree(work, ignore_errors=True)
    os.makedirs(work)
    st_path = os.path.join(work, "stf_plc.st")
    with open(st_path, "w") as f:
        f.write(src)
    r = subprocess.run([os.path.join(MATIEC, "iec2c"), "-I", os.path.join(MATIEC, "lib"), "stf_plc.st"],
                       cwd=work, capture_output=True, text=True)
    if r.returncode != 0:
        raise SystemExit("MatIEC rejected the program:\n" + r.stdout + r.stderr)
    located = re.findall(r"__LOCATED_VAR\((\w+),(\w+),(\w),(\w),(\d+)(?:,(\d+))?\)",
                         open(os.path.join(work, "LOCATED_VARIABLES.h")).read())
    with open(os.path.join(work, "glue.c"), "w") as f:
        f.write(glue(located))
    c_files = ["glue.c"] + [f for f in os.listdir(work) if f.endswith(".c") and f not in ("glue.c", "POUS.c")]
    wasm = os.path.join(work, "plc.wasm")
    cmd = [CLANG, "--target=wasm32-wasip1", f"--sysroot={SYSROOT}", f"-resource-dir={RUNTIMES}", "-O2", "-w",
           "-I", os.path.join(MATIEC, "lib", "C"), "-I", ".", "-mexec-model=reactor", f"-fuse-ld={WASM_LD}",
           *(f"-Wl,--export={e}" for e in EXPORTS), "-o", wasm, *c_files]
    r = subprocess.run(cmd, cwd=work, capture_output=True, text=True)
    if r.returncode != 0:
        raise SystemExit("clang failed:\n" + r.stdout + r.stderr)
    os.makedirs(out, exist_ok=True)
    shutil.copy(wasm, os.path.join(out, "plc.wasm"))
    with open(os.path.join(out, "stf_plc.st"), "w") as f:
        f.write(src)
    sha = hashlib.sha256(open(wasm, "rb").read()).hexdigest()[:16]
    meta = {"scan_ms": iec.SCAN_MS, "io": io, "image": IMAGE, "jobs": iec.JOBS,
            "job_units": {j: list(iec.RESERVE[j]) for j in iec.JOBS}, "layout": iec.LAYOUT,
            "units": iec.C.UNIT_ORDER, "states": starts, "wasm_sha": sha, "st_lines": src.count("\n"),
            "compiler": "MatIEC iec2c " + subprocess.run([os.path.join(MATIEC, "iec2c"), "-v"],
                                                         capture_output=True, text=True).stdout.split("\n")[0]}
    with open(os.path.join(out, "plc.json"), "w") as f:
        json.dump(meta, f, indent=1)
    return meta


if __name__ == "__main__":
    m = build()
    print(f"compiled: {m['st_lines']} lines of ST -> plc.wasm {m['wasm_sha']} ({m['compiler']})")
