"""Writes ~/workspace/stf-cad/handoff/HANDOFF_FREECAD_MCP.md - everything a fresh
Claude session needs to rebuild the complete STF factory in FreeCAD via the
FreeCAD MCP. The narrative is below; every number in the appendices is pulled
live from the models, so the handoff cannot drift from the source."""
import json, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import hbw_model as HM, vgr_model as VG, oven_model as OM, sorting_model as SM, plc_model as PM
import factory_layout as FL, components as C

OUT = os.path.expanduser("~/workspace/stf-cad/handoff/HANDOFF_FREECAD_MCP.md")
CTL = json.load(open(os.path.expanduser("~/workspace/stf-hw/web/public/controller.json")))

NARRATIVE = r'''
# STF digital twin: handoff for building the complete CAD in FreeCAD via the FreeCAD MCP

Generated by `stf-cad/hbw/make_handoff.py` on the date in the footer. Sections 1-9 are
written; the appendices (A-G) are dumped live from the Python models, so they are
exactly what the current generators build. **Re-run `python3 make_handoff.py` after any
model change.**

## 0. What to do in this session

Build the fischertechnik **Fabrik Simulation 24V (536634)** as a precise, coloured,
articulated FreeCAD model **inside a running FreeCAD, through the FreeCAD MCP**
(`mcp__freecad__run_script` / `mcp__freecad__send_command`). The Python parameter tables
in `~/workspace/stf-cad/hbw/` are the single source of truth: **generate** geometry from
them, never retype numbers.

Preconditions:
1. FreeCAD 1.1.3 GUI is running with the MCP add-on's RPC server started (Workbench
   "MCP Addon" -> Start RPC Server). If `run_script` returns "Connection refused", the
   server is not running; ask the user to start it.
2. First call: `run_script` with
   `import sys; sys.path.insert(0, '/Users/sohampatel/workspace/stf-cad/hbw')`,
   then `import hbw_model, vgr_model, oven_model, sorting_model, plc_model, factory_layout, detail`.
   After that you can build inside the live GUI document with the same code the headless
   builder uses (`stf_freecad.py`: container() / solid() / shape(); `detail.precise()`
   gives the chamfered/threaded/spring B-rep).
3. Advantage over headless: ViewObjects exist in the GUI, so set `ShapeColor`,
   `Transparency` and visibility directly. No `fcstd_colour.py` zip patching is needed.

Suggested order (verify each step before the next; take a view screenshot with
`FreeCADGui.ActiveDocument.ActiveView.saveImage(path, 1600, 1000, 'White')` and look at it):
1. Run every proof headless first (commands in section 8). Refuse to build if any fails.
2. New document `STF_Factory`. Build the white table, then the black ft base plates
   (Appendix B rects).
3. One module at a time, as nested `App::Part` containers **that ARE the joints**
   (HBW J1_Travel_X / J2_Lift_Z / J3_Ausleger_Y; VGR J_Swivel / J_Plunge / J_Reach;
   oven J_Ofenschieber / J_Ofentuer / J_Drehkranz / J_Sauger / J_Senken / J_Auswerfer;
   sorting J_Auswurf_weiss/rot/blau). The module placement is a rigid transform
   (Appendix B). Parts in module coordinates.
4. Replace every I/O part's primitive with the precise component
   (`stf-factory/cad/components/<id>.step` or `.FCStd`), placed by the `fit` block in
   `stf-hw/web/public/hbw_parts.json` (axis permutation + sign, det +1, real size, centred
   on the part envelope; see section 6).
5. PCBs, PLC cabinet, then wiring and hoses as swept tubes (`Part.Wire` + `makePipeShell`)
   from `hbw_parts.json` -> `wiring` (cables / bundles / power / hoses, colour per
   `wiring.roles`).
6. Save to `~/workspace/stf-factory/cad/STF_Factory_MCP.FCStd`, export STEP. Do not
   overwrite `STF_Factory.FCStd`, which is the headless build.

## 1. The project, and the user

- The user (Soham) is building a **portfolio-grade digital twin** (depth over breadth).
  The thesis: geometry, kinematics, control logic and the PLC I/O map normally live in
  different tools and silently disagree. Here ONE parameter table generates CAD,
  simulation, web view, drawings, parts tables, and proofs, and every consumer
  **refuses to build if a proof fails**.
- Repos:
  - `~/workspace/stf-cad/hbw`: the generators, the source of truth.
  - `~/workspace/stf-hw`: web twin (Vite/React/three.js on http://localhost:5173/stf/, API :8000).
  - `~/workspace/stf-factory`: production twin (web :5200, API :8100) and `cad/`, the CAD deliverables.
  - `~/stf`: the university repo (git.oth-aw.de, Prof. Wiehl), docs only, PDFs in `~/stf/docs/hw`.
- Headless tools: `/Applications/FreeCAD.app/Contents/Resources/bin/freecadcmd` (FreeCAD 1.1.3;
  under freecadcmd `__name__` is the module name, so scripts guard with
  `sys.argv[-1].endswith(...)`); `/Applications/Blender.app/Contents/MacOS/Blender -b -P`.
- Nothing has been committed to git yet (branch `feat/3d-twin-rearchitecture` in stf-hw).

## 2. Source documents (in `~/stf/docs/hw`)

- `536634-Fabrik_Simulation_24V.pdf` (the booklet, 42 pp.):
  - p.3-6: Belegungsplan per module (Appendix E);
  - p.7: PLC I/O type (P-reading inputs, P-switching outputs);
  - p.8-11: Bauteilbeschreibung (component descriptions);
  - p.12-41: models, processes, exercises. Key figures:
    - Abb. 4: membrane pump (Deckel, Membran, Kolben, Kurbeltrieb, Ein-/Auslassventil);
    - Abb. 5: 3/2-way solenoid valve (coil a, core b, spring c; ports 1 P, 2 A, 3 R);
    - Abb. 6: VGR kinematics;
    - Abb. 9: oven station areas;
    - Abb. 10: sorting line areas.
- `536634-Factory-simulation-24V-extended-description.pdf`: the 24 V adapter PCB and PLC
  interface (`controller.py` replicates it, 5 documented discrepancies).
- Datasheets:
  - 144643 encoder motor, 37783 mini switch, 36134 phototransistor, 128599 colour sensor;
  - RevPi Core / RevPi DIO (96 x 22.5 x 110.5 mm DIN housings);
  - Mean Well WDR (no dimensions printed);
  - occupancy plans (.ods) per module.

Facts from the booklet that shaped the model (do not re-derive):
- Process order (p.2): the VGR fills the HBW; the HBW stores by colour, then retrieves to
  the oven station; the processed pieces are sorted by colour into Lagerstellen; the VGR
  brings them back to the HBW. The workpieces START in the sorting Lagerstellen.
- **Oven station (p.30)**, in order:
  1. The VGR lays the workpiece on the extended Ofenschieber; light barrier I9 breaks.
  2. The door opens, the slider retracts, the piece is baked (Q9 lamp).
  3. The door opens and the slider extends; the station's **own** Sauggreifer puts the
     piece on the Drehtisch.
  4. The Drehtisch dwells under the Säge, then turns to the belt.
  5. The pneumatic Auswerfer pushes the piece onto the belt, which runs it through I3
     into the Sortierstrecke.
  6. Passing I3 sends the Drehtisch home, and the belt stops after a delay.
  - **No encoders** on the oven or the sorting line.
- **Sorting (p.35-36)**:
  - The colour sensor sends RED light and measures reflection; it is **NOT RGB**.
  - The inlet barrier starts the belt, and the piece passes a darkened lock (hood) with
    the sensor.
  - Two thresholds split white/red/blue. The I1 Impulstaster counts belt pulses so the
    ejector fires by distance, not time.
  - Bays nearest to farthest from the sensor are white, red, blue. Each bay has a barrier
    that can tell full from empty, but not how many pieces it holds.
- **Components (p.8-11)**:
  - Encoder motor: 24 V, 2.03 W at 214 rpm, 320 mA, 25:1, 3 pulses/motor-rev = 75/output-rev.
  - S-Motor: 24 V, max 300 mA, 5 mNm, 10 700 rpm, U-Getriebe 64.8:1 side output.
  - Compressor: 24 V, 0.7 bar, 70 mA, membrane pump.
  - Pneumatic cylinder: spring return; two coupled cylinders make the vacuum.
  - IR track sensor: 5-30 mm, 2 emitters + 2 receivers, push-pull, 9 V from the PCB.
  - Colour sensor: 0-9 V (booklet) vs 0-2 V (datasheet) vs 0-10 V (extended description).
    **MEASURE.**
  - 3/2 valve: energised 1 P -> 2 A, off 2 A -> 3 R; normally closed.
- Factory totals (extended description p.2): 26 DI, 10 counter, 1 AI, 35 outputs,
  24 V / 4.8 A.

## 3. Coordinate conventions (most bugs came from here)

- Every module is built and proven in its OWN frame, then placed by a rigid transform
  (it cannot introduce interference, so the module proofs carry over).
- **Factory frame:** the front edge of the table is x = 0 (+X runs to the back), "right"
  seen from the front is -Y, +Z up, mm.
- HBW, oven and sorting are rotated +90 deg about Z: module (x, y) -> factory
  (-y + TX, x + TY). The VGR and PLC are translated only.
- **Web viewer mirror bug (fixed):** three.js used v(x,y,z) = (x, z, y), a reflection, so
  the web twin drew the mirror image for its whole life. It is fixed with one
  scale(1,1,-1) group. FreeCAD/STEP/glTF were always right; no action is needed in
  FreeCAD.
- A moving thing's position must be DERIVED from the geometry that carries it, never a
  literal. A load in transit needs its own collision group.
- A FreeCAD document needs a ViewProvider for every object (containers too), a real
  camera, and hidden App::Origin planes, or the 3D view opens blank.

## 4. The layout (matched to the booklet cover photo, then 2x oven + sorting)

- Front row: sorting line (left) and oven station (right, set back).
- Back row: VGR (behind the sorting line) and HBW (behind the oven).
- PLC cabinet in the free corner in front of the oven.
- Table 1870 x 1510 mm, white, with black perforated ft base plates per module (15 mm grid).
- The oven belt ENDS against the sorting belt's back rail and hands the workpiece across
  the corner onto the sorting inlet. `OVEN_TX` is solved from that
  (`factory_layout._solve_oven_tx`).
- The HBW sits at TY=150 because the VGR's rear motor otherwise hits the mould waiting on
  the HBW belt while it serves the rot bay. vgr_path proves it.
- Plate SIZES are model sizes, **not yet measured at the lab**. The photo fixes the
  arrangement only. The user was going to measure the plates.

## 5. The modules (details in Appendix A, parts in Appendix G)

- **HBW 536631** (`hbw_model.py`):
  - rack 4 bays x 3 rows (12 slots), crane: travel X / lift Z / bidirectional Ausleger Y;
  - belt at x=665 with light barriers at both ends, a hood, toothed-belt drive;
  - 183 solids, `check()` 96 poses + `check_carry` + `check_path`.
- **VGR 536630** (`vgr_model.py`):
  - R-P-P: swivel Rz, plunge Z and reach, both threaded spindles (4 mm lead);
  - spring stem (6 mm) under the cup; cup radius 168..568;
  - `vgr_path.py` plans and sweeps the whole tour: belt -> oven tray -> rot bay -> belt,
    42 waypoints, ~2 200 swept poses.
- **Oven 536632** (`oven_model.py`, rebuilt to Abb. 9, then 2x):
  - ONE flow line x = 460: tray -> Sauger -> Drehtisch -> Auswerfer -> belt.
  - Q12 is a pneumatic cylinder with TWO positions, so tray top = disc top = belt top =
    Z_W 60, and ONE 50 mm stroke serves both Sauger stops (asserted).
  - Drehtisch stops: 0 Sauger, -90 Säge, -180 belt.
  - Interlocks proven: the slider moves only with the door open, Q12 lowers only at a
    stop, the Auswerfer fires only at the belt stop.
  - `check()`: 196 poses + the workpiece swept along its whole journey.
- **Sorting 536633** (`sorting_model.py`, mirrored to match the photos, then 2x):
  - belt +X, ejector cylinders BEHIND the belt pushing -Y, deep Lagerstellen in FRONT
    (factory: toward the VGR);
  - red hood (darkened lock) with the colour sensor 25 mm above the piece; I2 inlet,
    I3 after colour, I1 Impulstaster.
- **PLC cabinet** (`plc_model.py`):
  - DIN rail with WDR-120-24 PSU, RevPi Core 3, 3x RevPi DIO (14 in / 14 out each), and
    RevPi AIO (for A4); 12 feed terminals; a cable duct.
  - 36 DI+counter / 35 DO / 1 AI -> 3 DIO + AIO.
- **24 V adapter PCB** on every module:
  - 160 x 100 x 22 envelope (estimated): ST1/ST2 to the model, ST3 34-pin to the PLC,
    terminals 1-30, relays R1-R8, valve terminals V1-V4.
  - Bidirectional motors via relay pairs; both on = stop, not a short.

## 6. Precise components (`components.py` -> `components_cad.py`)

- Nine components are built as FreeCAD B-rep with sub-parts, checked to 0.01 mm against
  their table: encoder_motor 144643, mini_switch 37783, phototransistor 36134,
  colour_sensor 128599, s_motor, compressor, pneumatic_cylinder, ir_track_sensor 128598,
  solenoid_valve.
- Files: `~/workspace/stf-factory/cad/components/<id>.FCStd|.step` +
  `FREECAD_AI_PROMPTS.md`.
- Every dimension carries a source tag: datasheet / booklet / photo / ft-std / assumed
  (MEASURE). Only datasheet values justify a 0.1 mm claim; the booklet parts' sizes are
  all "assumed".
- Which model part IS which component: `parts_table._kind` (from the Belegungsplan).
  - Encoder motor only where B-channels are wired; every other motor is an S-Motor.
  - Light-barrier receivers are phototransistors; the transmitters are LEDs (not modelled).
  - The HBW's A1/A2 are ONE IR track sensor with 2 channels (the model draws two parts).
- **Fit** (`wiring.fit`): the component's overall bbox is laid into the part envelope by
  the axis permutation with the least error, det +1, at REAL size (never stretched),
  centred. The result is in `hbw_parts.json` as `fit {comp, perm, sign, centre, origin}`.
  FreeCAD placement: `Placement(centre) * Rotation(basis cols = sign_i * e_perm_i) *
  Placement(-origin)`.

## 7. Wiring (`wiring.py`, IEC colours)

- Colours: +24V red, 0V blue, PE green-yellow, mains L brown / N light blue, DI white,
  DO orange, ENC yellow, AI violet, AIR = translucent PU hose (not a wire).
- What each cable carries:
  - Sensor: +24V and DI.
  - LED transmitter: +24V and 0V.
  - Colour sensor: +24V, AI, 0V.
  - Actuator (valve, compressor, lamp, one-way motor): DO and 0V.
  - Bidirectional motor: DO and DO.
  - Pneumatic cylinders get HOSES from their valve, and the compressor feeds each valve.
- Routes lie on the table (z ~1.2), Manhattan with bend radius 10.
  - Each module PCB -> PLC duct: a bundle of single wires (every ST3 signal + 2x +24V +
    2x 0V).
  - In the cabinet: mains L/N/PE -> PSU; PSU -> terminals 1/4; PE -> DIN rail;
    terminals -> duct.
- Parts on moving frames are NOT wired yet (they would need drag chains): an open item.

## 8. Commands (run from `~/workspace/stf-cad/hbw`)

```
python3 hbw_model.py; python3 vgr_model.py; python3 oven_model.py; python3 sorting_model.py
python3 plc_model.py; python3 vgr_path.py; python3 pipeline.py
python3 -c "import factory_layout as F; print(F.check_cross())"      # must print []
python3 hbw_export.py        # -> stf-hw/web/public/hbw_parts.json (fits + wiring included)
python3 parts_table.py       # -> stf_parts.csv/.xlsx
python3 controller.py        # -> controller.json + reconciliation with the Belegungsplan
/Applications/FreeCAD.app/Contents/Resources/bin/freecadcmd build_cad.py          # headless FCStd+STEP+glb
/Applications/FreeCAD.app/Contents/Resources/bin/freecadcmd components_cad.py     # the 9 components
python3 make_handoff.py      # regenerate THIS file
```
Web: `npm run dev --prefix ~/workspace/stf-hw/web` -> http://localhost:5173/stf/
(views: complete setup, oven close-up, oven blueprint, controller board, 9 components).

## 9. Open items and things to measure at the lab

- Real plate sizes and positions of all four modules, and the PCB size.
- Sizes of the five booklet components (S-Motor, compressor, cylinder, IR sensor, valve).
- Colour sensor output range (three documents disagree).
- The VGR I3 reference position (the rear motor overhangs the table at home).
- Wiring to moving parts (drag chains).
- The IR track sensor's "black" logic level.
- The HBW's A1/A2 should be modelled as one 2-channel part.
- Oven: whether the real belt meets the sorting inlet at a corner exactly like this. That
  was inferred from the cover photo.
'''


def dump(d):
    return "\n".join(f"    {k} = {v!r}" for k, v in d.items())


def parts_table(parts, title):
    rows = [f"\n### {title}\n", "| part | group | frame | kind | p (x,y,z) | size | tag | support |",
            "|---|---|---|---|---|---|---|---|"]
    for p in parts:
        if p.group == "frame":
            continue
        s = p.s if p.kind == "box" else f"{p.s[0]}-axis L{p.s[1]} D{p.s[2]}"
        rows.append(f"| {p.name} | {p.group} | {getattr(p, 'frame', getattr(p, 'joint', ''))} | {p.kind} | "
                    f"{tuple(round(v, 2) for v in p.p)} | {s} | {p.tag} | {p.support} |")
    return "\n".join(rows)


def main():
    out = [NARRATIVE.strip(), "\n\n---\n# Appendices (generated from the models)\n"]
    out.append("## A. Parameter tables\n")
    for name, d in (("hbw_model.P", HM.P), ("vgr_model.V", VG.V), ("oven_model.O", OM.O),
                    ("sorting_model.S", SM.S), ("plc_model.C", PM.C)):
        out.append(f"### {name}\n```\n{dump(d)}\n```")
    out.append("## B. Factory placement\n```")
    out.append(f"table PLATE = {FL.PLATE}")
    out.append(f"HBW   rot +90  TX, TY = {FL.TX}, {FL.TY}   rect {FL.module_rect()}")
    out.append(f"VGR   translate VGR_AT = {FL.VGR_AT}          rect {FL.vgr_rect()}  tower {FL.vgr_tower()}")
    out.append(f"OVEN  rot +{FL.OVEN_ROT}  TX, TY = {FL.OVEN_TX}, {FL.OVEN_TY}  rect {FL.oven_rect()}")
    out.append(f"SORT  rot +{FL.SORT_ROT}  TX, TY = {FL.SORT_TX}, {FL.SORT_TY}  rect {FL.sort_rect()}")
    out.append(f"PLC   translate PLC_AT = {FL.PLC_AT}           rect {FL.plc_rect()}")
    out.append("```")
    out.append("## C. VGR stations (solved)\n```")
    for k, v in FL.stations().items():
        out.append(f"{k:10s} {v}")
    out.append("```")
    out.append("## D. Joints and proven stops\n```")
    out.append(f"oven STATIONS (turn deg) = {OM.STATIONS}; AXES = {OM.AXES}")
    out.append(f"oven SLIDER {OM.O['SLIDER']} DOOR_Z {OM.O['DOOR_Z']} SAUGER {OM.O['SAUGER']} "
               f"LOWER {OM.O['LOWER']} PUSH {OM.O['PUSH']}")
    out.append(f"sorting EJECT {SM.S['EJECT']} axis {SM.EJECT_AXIS}; Lagerstellen {SM.handover_points()}")
    out.append(f"VGR PLUNGE {VG.V['PLUNGE']} REACH {VG.V['REACH']} SWIVEL {VG.V['SWIVEL']} TRANSIT {VG.V['TRANSIT']}")
    out.append("```")
    out.append("## E. Belegungsplan (terminal -> signal), per module\n")
    for m, d in CTL["modules"].items():
        out.append(f"### {m}: {d['name']} ({d['ft']})\n```")
        out.append(" ".join(f"{k}:{v}" for k, v in sorted(d["st3"].items(), key=lambda kv: int(kv[0]))))
        out.append(f"relays {json.dumps(d.get('relays'))}\nvalves {json.dumps(d.get('valves'))}")
        out.append("```")
    out.append("## F. Components (housing dims and sources)\n")
    for cid, c in C.COMPONENTS.items():
        dims = ", ".join(f"{x['key']}={x['value']:g} ({x['source']})" for x in c["dims"])
        facts = "; ".join(f"{a}: {b}" for a, b, _ in c["facts"])
        out.append(f"- **{cid}** ft {c['ft']}, {c['name_de']}. Material: {c['material']}.\n"
                   f"  Dims: {dims}.\n  Facts: {facts}")
    out.append("\n## G. Every solid, per module (module frame, authoring pose)")
    out.append(parts_table(HM.build(HM.P["CV_X"], 260.0, 0.0), "HBW"))
    out.append(parts_table(VG.build(), "VGR"))
    out.append(parts_table(OM.build(), "Oven"))
    out.append(parts_table(SM.build(), "Sorting"))
    out.append(parts_table(PM.build(), "PLC cabinet"))
    import datetime
    out.append(f"\n\n_Generated {datetime.date.today()} by stf-cad/hbw/make_handoff.py._\n")
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, "w").write("\n".join(out))
    print(f"wrote {OUT} ({os.path.getsize(OUT) / 1024:.0f} kB)")


if __name__ == "__main__":
    main()
